config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets
  root 'tweets#index'
  post '/tweets/new',to:'tweets#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message, presence: true, length: { maximum: 140 }
    validates :tdate, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
        protect_from_forgery except: :search # searchアクションを除外
    def index
        @tweets = Tweet.all
    end
    def new
     @tweet = Tweet.new
    end
    def create
     message= params[:tweet][:message]
     tdate = params[:tweet][:tdate]
     @tweet = Tweet.new(message: message, tdate: tdate)
     if @tweet.save
       flash[:notice] = "1 record added"
       redirect_to root_path
     else
       render 'new'
     end
    end
    def destroy
     tweet = Tweet.find(params[:id])
     tweet.destroy
     redirect_to root_path
    end
    def edit
     @tweet = Tweet.find(params[:id])
    end
    def update
     message= params[:tweet][:message]
     tdate = params[:tweet][:tdate]
     @tweet = Tweet.find(params[:id])
     @tweet.update(message: message, tdate: tdate)
     if @tweet.save
       flash[:notice] = "1 record update"
       redirect_to root_path
     else
       render 'edit'
     end
    end
    def show
     @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div id ="container">
      <div id="header">
        <%= render "header" %>
      </div>
      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      <div id="content">
        <%= yield %>
      </div>
      <div id="footer">
        <%render "footer" %>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_footer.html.erb
<p>Copyright kindai Unibersity 2019 All rights Reserved</p>

app/views/tweets/_form.html.erb
 <p>
  <%= f.label :message, 'message' %>
  <p><%= f.text_area :message ,size: "25x7"%></p>
  <p><%= "max 140"%></p>

 </p>
 <%= f.submit 'submit' %>

app/views/tweets/_header.html.erb
<p class="image-to-circle"></p>
<a href='tweets/new' class="btn-squareR" >tweet</a>

app/views/tweets/_sidebar.html.erb
 <p class="trim-image-to-circle"></p>
  <h1>近畿大学</h1>
  <p>@kinkidaigakuPR</p>
　　　 
  <p>近畿大学のTwitter公式アカウントです。気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。
               マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。
               履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。
  </p>
  <ul>
   <li><a>大阪府東大阪市</a></li>
   <li><a href="https://www.instagram.com/kindaiuniversity/">instagram</a></li>
  </ul>
  <a href='tweets/new' class="btn-square">tweet</a>

app/views/tweets/edit.html.erb
<% if @tweet.errors.present? %>
<h3>There is an error.</h3>
<ul>
 <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
 <% end %>
</ul>
<% end %>

<%= form_for @tweet , name: {action: :update} do |f| %>
 <%= render "form" ,f:f%>
 <% @tweet.tdate = @tweet.tdate %>
 <%= f.hidden_field :tdate %>
<% end %>
<p><%= link_to 'Back', root_path %></p>

app/views/tweets/index.html.erb
<head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="css/style.css">
    
</head>



<% if flash[:notice]%>
 <%= flash[:notice]%>
<% end %>


<% @tweets.each do |tweet| %>
<hr>
<p>
    <% t1 = Time.current %>
    <% t2 = tweet.tdate %>
    <% t = t1 - t2 %>
    <p>近畿大学 @kinkidaigakuPR   <%=t.ceil%><%="秒前"%></p>
    <%= tweet.message %>
    <%= link_to 'delete', tweet_path(tweet.id),method: :delete %>
    <%= link_to 'show', tweet_path(tweet.id) %>
    <%= link_to 'edit', edit_tweet_path(tweet.id) %>
</p>
<hr>
<% end %>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>There is an error.</h3>
<ul>
 <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
 <% end %>
</ul>
<% end %>

<p>
 <%= form_for @tweet , name: {action: :create} do |f| %>
 <%= render "form" ,f:f%>
 <% @tweet.tdate = Time.current %>
 <%= f.hidden_field :tdate %>
 <p><%= link_to 'Back', root_path %></p>
<% end %>
</p>

app/views/tweets/show.html.erb
<p>
    <strong>date:</strong>
    <%= @tweet.tdate %>
</p>

<div style="display:inline-block;padding: 10px; margin-bottom: 10px; border: 1px solid #333333;">
   <p>
    <strong>tweet:</strong>
    <p><%= @tweet.message %></p>
</p>
</div>

<%= link_to 'Back', root_path %>